it should be correct

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -13,44 +13,39 @@ jobs:
       - name: Checkout repository
         uses: actions/checkout@v2
 
-#      - name: Set up Java
-#        uses: actions/setup-java@v2
-#        with:
-#          distribution: 'adopt'
-#          java-version: '11'
+      - name: Set up Java
+        uses: actions/setup-java@v2
+        with:
+          distribution: 'adopt'
+          java-version: '11'
 
       - name: Set up Docker
         uses: docker/setup-buildx-action@v1
 
+      - name: Build and test Spring Boot
+        run: mvn clean install -DskipTests
+
+      - name: Check test results
+        run: |
+          if [ $? -eq 0 ]; then
+            echo "Tests passed. Proceeding to the next stage."
+          else
+            echo "Tests failed. Exiting."
+            exit 1
+          fi
+
       - name: Build Docker containers
         run: |
-          echo CR_PAT è questa ${{ secrets.CR_PAT }}
+          TAG=0.0.0
+          docker-compose build
           docker login ghcr.io -u $GITHUB_REPOSITORY -p ${{ secrets.CR_PAT }}
-
-#      - name: Build and test Spring Boot
-#        run: mvn clean install -DskipTests
-#
-#      - name: Check test results
-#        run: |
-#          if [ $? -eq 0 ]; then
-#            echo "Tests passed. Proceeding to the next stage."
-#          else
-#            echo "Tests failed. Exiting."
-#            exit 1
-#          fi
-#
-#      - name: Build Docker containers
-#        run: |
-#          TAG=0.0.0
-#          docker-compose build
-#          docker login ghcr.io -u $GITHUB_REPOSITORY -p "$CR_PAT"
-#          docker tag $GITHUB_REPOSITORY_NAME/rest-db:latest ghcr.io/$GITHUB_REPOSITORY/rest-db:$TAG
-#          docker tag $GITHUB_REPOSITORY_NAME/rest:latest ghcr.io/$GITHUB_REPOSITORY/rest:$TAG
-#          docker tag $GITHUB_REPOSITORY_NAME/keycloak-db:latest ghcr.io/$GITHUB_REPOSITORY/keycloak-db:$TAG
-#          docker tag $GITHUB_REPOSITORY_NAME/keycloak:latest ghcr.io/$GITHUB_REPOSITORY/keycloak:$TAG
-#          docker tag $GITHUB_REPOSITORY_NAME/frontend:latest ghcr.io/$GITHUB_REPOSITORY/frontend:$TAG
-#          docker push ghcr.io/$GITHUB_REPOSITORY/rest-db:$TAG
-#          docker push ghcr.io/$GITHUB_REPOSITORY/rest:$TAG
-#          docker push ghcr.io/$GITHUB_REPOSITORY/keycloak-db:$TAG
-#          docker push ghcr.io/$GITHUB_REPOSITORY/keycloak:$TAG
-#          docker push ghcr.io/$GITHUB_REPOSITORY/frontend:$TAG
+          docker tag $GITHUB_REPOSITORY_NAME/rest-db:latest ghcr.io/$GITHUB_REPOSITORY/rest-db:$TAG
+          docker tag $GITHUB_REPOSITORY_NAME/rest:latest ghcr.io/$GITHUB_REPOSITORY/rest:$TAG
+          docker tag $GITHUB_REPOSITORY_NAME/keycloak-db:latest ghcr.io/$GITHUB_REPOSITORY/keycloak-db:$TAG
+          docker tag $GITHUB_REPOSITORY_NAME/keycloak:latest ghcr.io/$GITHUB_REPOSITORY/keycloak:$TAG
+          docker tag $GITHUB_REPOSITORY_NAME/frontend:latest ghcr.io/$GITHUB_REPOSITORY/frontend:$TAG
+          docker push ghcr.io/$GITHUB_REPOSITORY/rest-db:$TAG
+          docker push ghcr.io/$GITHUB_REPOSITORY/rest:$TAG
+          docker push ghcr.io/$GITHUB_REPOSITORY/keycloak-db:$TAG
+          docker push ghcr.io/$GITHUB_REPOSITORY/keycloak:$TAG
+          docker push ghcr.io/$GITHUB_REPOSITORY/frontend:$TAG
